# Generated by Django 2.1.5 on 2020-05-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_article_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
    ]
