# Generated by Django 2.1.5 on 2020-05-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20200526_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='article',
            name='content_area',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
