# Generated by Django 2.1.5 on 2020-05-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20200526_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='')),
                ('image_path', models.TextField(blank=True, max_length=1000, null=True, verbose_name='')),
            ],
        ),
    ]
