# Generated by Django 2.1.5 on 2020-05-27 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='category',
            new_name='article_id',
        ),
    ]
